### ISSUE TITLE
Cloning error

### ISSUE THREAD

**Issue by kewp** [mgerhardy/fips-accidentalnoise#1]
Trying to clone this with

> ./fips clone fips-accidentalnoise

Getting error

> Clone of 'https://code.google.com/p/accidental-noise-library/' into submodule path 'accidental-noise-library' failed

I think the module has moved to https://code.google.com/archive/p/accidental-noise-library/. So the .gitmodules needs to be updated

**Comment by mgerhardy** [comment]
https://github.com/JTippetts/accidental-noise-library

picked that clone
